#!/bin/bash
tar xf attr-2.4.48.tar.gz 
cd attr-2.4.48
./configure --prefix=$1/usr --disable-static --sysconfdir=$1/etc --docdir=$1/usr/share/doc/attr-2.4.48 --host=$4
make -j$2
make install
cd ..
rm -rf attr-2.4.48

