#!/bin/bash
tar xf acl-2.2.53.tar.gz 
cd acl-2.2.53
CFLAGS="$CFLAGS --sysroot=$1" ./configure --prefix=$1/usr --disable-static --libexecdir=$1/usr/lib --docdir=$1/usr/share/doc/acl-2.2.53 --host=$4
make -j$2
make install
cd ..
rm -rf acl-2.2.53

