#!/bin/bash
tar xf perl-5.30.1.tar.xz 
cd perl-5.30.1
echo "127.0.0.1 localhost $(hostname)" > $1/etc/hosts
export BUILD_ZLIB=False
export BUILD_BZIP2=0
sh Configure -des -Dprefix=$1/usr -Dvendorprefix=$1/usr -Dman1dir=$1/usr/share/man/man1 -Dman3dir=$1/usr/share/man/man3 -Dpager="$1/usr/bin/less -isR" -Duseshrplib -Dusethreads -Doptimize=-O$3 -Dcc=$CC
make -j$2
make install
unset BUILD_ZLIB BUILD_BZIP2
cd ..
rm -rf perl-5.30.1

