#!/bin/bash
tar xf less-551.tar.gz 
cd less-551
CFLAGS="$CFLAGS --sysroot=$1 -I$1/usr/include/ncursesw" LDFLAGS="$LDFLAGS --sysroot=$1" ./configure --prefix=$1/usr --sysconfdir=$1/etc --host=$4
make -j$2
make install
cd ..
rm -rf less-551


