#!/bin/bash
tar xf procps-ng-3.3.15.tar.xz 
cd procps-ng-3.3.15
ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes CFLAGS="$CFLAGS -L$1/usr/lib -I$1/usr/include/ncursesw" ./configure --prefix=$1/usr --exec-prefix=$1 --libdir=$1/usr/lib --disable-static --disable-kill --host=$4
make -j$2
make install
mv -v $1/usr/lib/libprocps.so.* $1/lib
ln -sfv ../../lib/$(readlink $1/usr/lib/libprocps.so) $1/usr/lib/libprocps.so
cd ..
rm -rf procps-ng-3.3.15


