#!/bin/bash
tar xf vim-8.2.0190.tar.gz 
cd vim-8.2.0190
echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h
./configure --prefix=$1/usr --host=$4
make -j$2
make install
ln -sv vim $1/usr/bin/vi
for L in $1/usr/share/man/{,*/}man1/vim.1; do ln -sv vim.1 $(dirname $L)/vi.1; done
cat > $1/etc/vimrc << "EOF"
" Begin /etc/vimrc
" Ensure defaults are set before customizing settings, not after
source $VIMRUNTIME/defaults.vim
let skip_defaults_vim=1 
set nocompatible
set backspace=2
set mouse=
syntax on
if (&term == "xterm") || (&term == "putty")
 set background=dark
endif
" End /etc/vimrc
EOF
cd ..
rm -rf vim-8.2.0190


