#!/bin/bash
tar xf procps-ng-3.3.15.tar.xz 
cd procps-ng-3.3.15
./configure --prefix=$1/usr --exec-prefix= --libdir=$1/usr/lib --docdir=$1/usr/share/doc/procps-ng-3.3.15 --disable-static --disable-kill --host=$4
make -j$2
make install
mv -v $1/usr/lib/libprocps.so.* $1/lib
ln -sfv ../../lib/$(readlink $1/usr/lib/libprocps.so) $1/usr/lib/libprocps.so
cd ..
rm -rf procps-ng-3.3.15


