#!/bin/bash
tar xf util-linux-2.35.1.tar.xz 
cd util-linux-2.35.1
mkdir -pv $1/var/lib/hwclock
rm -vf $1/usr/include/{blkid,libmount,uuid}
./configure ADJTIME_PATH=$1/var/lib/hwclock/adjtime --docdir=$1/usr/share/doc/util-linux-2.35.1 --disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-setpriv --disable-runuser --disable-pylibmount --disable-static --without-python --prefix=$1 --host=$4
make -j$2
make install
cd ..
rm -rf util-linux-2.35.1


